version: '3.8'

services:
  ssfuzz:
    container_name: ssfuzz
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/root/ssfuzz
    tty: true
    restart: always
    ports:
      - 10347:10347
      - 8888:8888
      - 11100:11100
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: "all"
              capabilities: ["gpu"]
  mysql:
   restart: always
   image: mysql:8.0
   container_name: mysql
   volumes:
     - ./env/init:/docker-entrypoint-initdb.d
   environment:
       - MYSQL_ROOT_PASSWORD=123456
       - MYSQL_DATABASE=ssfuzz
   ports:
       - "10346:3306"
